[package]
name = "craycray"
version = "0.1.0"
authors = ["Vzaa <Vzaa@users.noreply.github.com>"]

[dependencies]
sdl2 = "0.29.1"
vecmath = "0.3.0"
rayon = "0.7.0"
clap = "2.23.3"
serde = "1.0.2"
serde_derive = "1.0.2"
serde_json = "1.0.1"
